apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: x6fi62df8-python 
  janus-idp.io/tekton: x6fi62df8-python
  backstage.io/kubernetes-id: x6fi62df8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x6fi62df8-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml